name: Python

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        id: python-version
        run: |
          python -c "import sys; open('python-version.txt', 'w').write(sys.version)"
          cat python-version.txt
      - name: Upload Python version artifact
        uses: actions/upload-artifact@v2
        with:
          name: python-version
          path: ./python-version.txt
